# Generated by Django 5.0.6 on 2024-07-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_call',
            field=models.BooleanField(default=False),
        ),
    ]
